name: mehery_sender
description: A Flutter package to send device tokens to a server.
version: 0.0.2
homepage: https://github.com/cerebusY2K/mehery_sender_flutter

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0 # For HTTP requests
  app_set_id: ^1.2.0 # For app-specific identification (if used)
  firebase_messaging: ^14.0.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# Flutter specific settings
flutter:
# You can add asset configurations if you plan to add assets in your package
# assets:
#   - images/example.png

# Fonts (if applicable)
# fonts:
#   - family: CustomFont
#     fonts:
#       - asset: fonts/CustomFont-Regular.ttf
